CadeteriaRemake/Controllers/CadeteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using CadeteriaRemake.Entidades;
using CadeteriaRemake.Models;
using CadeteriaRemake.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;

namespace CadeteriaRemake.Controllers
{
    public class CadeteController : Controller
    {
        private readonly IMapper _mapper;
        public CadeteController(IMapper mapper)
        {
            _mapper = mapper;
        }

        private RepositorioCadete repo = new RepositorioCadete();

        public ActionResult Index()
        {
            List<Cadete> cadetes = repo.obtenerCadetes(1);
            List<CadeteViewModel> cadetesVM = _mapper.Map<List<CadeteViewModel>>(cadetes);
            return View(cadetesVM);
        }


        [HttpPost]
        public ActionResult AltaCadete(Cadete cadete)
        {
            if (repo.altaCadete(cadete))
            {
                return Redirect("~/Cadete");
            }
            else
            {
                return View();
            }
        }
        public ActionResult BajaModificacion()
        {
            List<Cadete> cadetes = repo.obtenerCadetes(0);
            List<CadeteViewModel> cadetesVM = _mapper.Map<List<CadeteViewModel>>(cadetes);
            return View(cadetesVM);
        }

        [HttpPost]
        public ActionResult EliminarCadete(string id) {
            if (repo.eliminarCadete(id))
            {
                return Redirect("~/Cadete/BajaModificacion");
            }
            else
            {
                return Redirect("~/Cadete/BajaModificacion");
            }
        }

        [HttpPost]
        public ActionResult ModificacionCadete(Cadete cadete)
        {
            if (repo.modificacionCadete(cadete))
            {
                return Redirect("~/Cadete/BajaModificacion");
            }
            else
            {
                return Redirect("~/Cadete/BajaModificacion");
            }            
        }

        public ActionResult AgregarCadete()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ObtenerCadete(string id)
        {
            if(id != null || id != "")
            {
                return View(repo.obtenerCadete(id));
            }
            else
            {
                return View(null);
            }
        }
    }
}

CadeteriaRemake/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using CadeteriaRemake.Entidades;
using CadeteriaRemake.ViewModels;
using ClienteriaRemake.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;

namespace CadeteriaRemake.Controllers
{
    public class ClienteController : Controller
    {
        private RepositorioCliente repo = new RepositorioCliente();

        private readonly IMapper _mapper;
        public ClienteController(IMapper mapper)
        {
            _mapper = mapper;
        }

        // GET: ClienteController

        public ActionResult Index()
        {
            List<Cliente> clientes = repo.obtenerClientes(1);
            List<ClienteViewModel> clientesVM = _mapper.Map<List<ClienteViewModel>>(clientes);
            if (clientesVM.Count > 0)
            {
                return View(clientesVM);
            }
            else
            {
                return View(null);
            }
        }

        public ActionResult AgregarCliente()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AltaCliente(Cliente cliente)
        {
            cliente.Estado = 1;
            if (repo.altaCliente(cliente))
            {
                return Redirect("~/Cliente");
            }
            else
            {
                return Redirect("~/Cliente");
            }
        }
        public ActionResult BajaModificacion()
        {

            List<Cliente> clientes = repo.obtenerClientes(1);
            List<ClienteViewModel> clientesVM = _mapper.Map<List<ClienteViewModel>>(clientes);
            if (clientesVM.Count > 0)
            {
                return View(clientesVM);
            }
            else
            {
                return View(null);
            }
        }

        [HttpPost]
        public ActionResult EliminarCliente(string id)
        {
            if(repo.eliminarCliente(id))
            {
                return Redirect("~/Cliente/BajaModificacion");
            }
            else
            {
                return Redirect("~/Cliente/BajaModificacion");
            }
        }

        [HttpPost]
        public ActionResult ModificacionCliente(Cliente cliente)
        {
            if (repo.modificacionCliente(cliente))
            {
                return Redirect("~/Cliente/BajaModificacion");
            }
            else
            {
                return Redirect("~/Cliente/BajaModificacion");
            }
        }

        [HttpPost]
        public ActionResult ObtenerCliente(string id)
        {
            if (id != null || id != "")
            {
                return View(repo.obtenerCliente(id));
            }
            else
            {
                return View(null);
            }
        }
    }
}

CadeteriaRemake/Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using CadeteriaRemake.Entidades;
using CadeteriaRemake.Models;
using CadeteriaRemake.ViewModels;
using ClienteriaRemake.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CadeteriaRemake.Controllers
{
    public class PedidoController : Controller
    {
        private readonly IMapper _mapper;

        private RepositorioPedido repoPedido = new RepositorioPedido();
        private RepositorioCliente repoCliente = new RepositorioCliente();
        private RepositorioCadete repoCadete = new RepositorioCadete();
        public PedidoController(IMapper mapper)
        {
            _mapper = mapper;
        }
        public ActionResult Index()
        {
            List<Pedido> pedidos = repoPedido.obtenerPedidos();
            List<PedidoViewModel> pedidosVM = _mapper.Map<List<PedidoViewModel>>(pedidos);
            return View(pedidosVM);
        }
        public ActionResult InformeCadetePedido()
        {
            List<PedidoViewModel> pedidos = repoPedido.obtenerInforme();
            return View(pedidos);
        }
        public ActionResult AgregarPedido()
        {
            List<Cadete> cadetes = repoCadete.obtenerCadetes(1);
            List<Cliente> clientes = repoCliente.obtenerClientes(1);
            List<SelectListItem> optionsCadeteVM = _mapper.Map<List<SelectListItem>>(cadetes);
            List<SelectListItem> optionsClienteVM = _mapper.Map<List<SelectListItem>>(clientes);

            AltaPedidoViewModel pedidoVM = new AltaPedidoViewModel();
            pedidoVM.cadetes = optionsCadeteVM;
            pedidoVM.clientes = optionsClienteVM;
            return View(pedidoVM);
        }


        [HttpPost]
        public ActionResult AltaPedido(AltaPedidoViewModel pedido)
        {
            if (repoPedido.altaPedido(pedido))
            {
                return Redirect("~/Pedido");
            }
            else
            {
                return Redirect("~/Pedido");
            }
        }

        [HttpPost]
        public ActionResult ModificacionPedido(EditarPedidoViewModel pedido)
        {
            if (repoPedido.editarPedido(pedido))
            {
                return Redirect("~/Pedido/BajaModificacion");
            }
            else
            {
                return Redirect("~/Pedido/BajaModificacion");
            }
        }


        public ActionResult BajaModificacion()
        {
            List<Pedido> pedidos = repoPedido.obtenerPedidos();
            List<PedidoViewModel> pedidosVM = _mapper.Map<List<PedidoViewModel>>(pedidos);
            return View(pedidosVM);
        }

        [HttpPost]
        public ActionResult ObtenerPedido(string id)//AltaPedidoViewModel pedido
        {
            List<Cadete> cadetes = repoCadete.obtenerCadetes(1);
            List<SelectListItem> optionsCadeteVM = _mapper.Map<List<SelectListItem>>(cadetes);
            EditarPedidoViewModel pedidoVM = new EditarPedidoViewModel();
            pedidoVM = repoPedido.obtenerPedido(id);
            pedidoVM.cadetes = optionsCadeteVM;
            return View(pedidoVM);
        }

        [HttpPost]
        public ActionResult EliminarPedido(string id)
        {
            if (repoPedido.eliminarPedido(id))
            {
                return Redirect("~/Pedido/BajaModificacion");
            }
            else
            {
                return Redirect("~/Pedido/BajaModificacion");
            }
        }

    }
}

CadeteriaRemake/Views/Shared/_Layout.cshtml
@model CadeteriaRemake.Entidades.Usuario;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CadeteriaRemake</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
    <header>
        <div class="container-fluid bg-primary">
            <nav class="container navbar navbar-expand-lg navbar-dark bg-primary mb-4" data-toggle-duration="300" data-side-color="dark" data-letter-color="">
                <!--Podemos dejar los data vacios-->
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">Navbar</a>
                    <!--<button class="btn btn-transparent" type="button">
                    navbar-toggler => btn btn-transparent -->
                    <!-- <span class="navbar-toggler-icon"></span>
                    </button>-->
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <!-- collapse navbar-collapse => d-none -->
                        <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button"
                                   data-toggle="dropdown" aria-expanded="false">
                                    Cadetes
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="Cadete" asp-action="Index">Listado de Cadetes</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Cadete" asp-action="AgregarCadete">Alta</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Cadete" asp-action="BajaModificacion">Modificacion y Baja</a>
                                </ul>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button"
                                   data-toggle="dropdown" aria-expanded="false">
                                    Clientes
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="Cliente" asp-action="Index">Listado de Clientes</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Cliente" asp-action="AgregarCliente">Alta</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Cliente" asp-action="BajaModificacion">Modificacion y Baja</a>
                                </ul>
                            </li>

                            <li class="nav-item dropdown active">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                   data-toggle="dropdown" aria-expanded="false">
                                    Pedidos
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="Pedido" asp-action="Index">Pedidos</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Pedido" asp-action="AgregarPedido">Alta</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Pedido" asp-action="BajaModificacion">Modificacion y Baja</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Pedido" asp-action="InformeCadetePedido">Informe Cadete / Jornal</a>
                                </ul>
                            </li>
                            <button type="button" class="btn btn-info" data-toggle="modal" data-target="#exampleModal">
                                Iniciar Sesion
                            </button>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </header>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Iniciar Sesion</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form class="form" asp-controller="Home" asp-action="InicioSesion">
                        <label>Usario</label>
                        <input type="text" class="form-control" placeholder="Usuario..." maxlength="20" asp-for="Nombre_usuario" required />
                        <label>Contraseña</label>
                        <input type="password" class="form-control" placeholder="Contraseña..." maxlength="10" asp-for="Contra" required />
                        <button type="submit" class="btn btn-primary btn-block">Ingresar</button>
                    </form>
                </div>
                <div class="modal-footer"></div>
            </div>
        </div>
    </div>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted navbar-dark bg-dark">
        <div class="container">
            &copy; 2020 - CadeteriaRemake - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>